version: 3.2.{build}-pre
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- ps: >-
    nuget restore
build:
  verbosity: minimal
after_build:
- ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION src\Elmah.Io.Functions\Elmah.Io.Functions.csproj --output artifacts
artifacts:
- path: 'src\**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 9XpSybqiIbTFiTdfkpUaBSMdLFCm4yx/MYR7KtYbV18g5gP5L6U8bhhOPfi/56o+